upstream django_app {
    server web:8000;
}

# 1. Redirect HTTP (Port 80) ke HTTPS (Port 443)
server {
    listen 80;
    server_name nama_domain_anda.com;
    return 301 https://$host$request_uri;
}

# 2. Konfigurasi Utama HTTPS (Port 443)
server {
    listen 443 ssl;
    server_name nama_domain_anda.com;
    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/nama_domain_anda.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nama_domain_anda.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/mediafiles/;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }
}